# Generated by Django 5.2.1 on 2025-05-14 06:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surgeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('specialization', models.CharField(blank=True, default='Ортопед-травматолог', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('height', models.FloatField(help_text='В сантиметрах', verbose_name='Рост (см)')),
                ('weight', models.FloatField(verbose_name='Вес (кг)')),
                ('bmi', models.FloatField(editable=False, verbose_name='ИМТ')),
                ('coxarthrosis_type', models.CharField(choices=[('PRIMARY', 'Первичный'), ('DYSPLASTIC', 'Диспластический'), ('POSTTRAUMATIC', 'Посттравматический'), ('OTHER', 'Другой')], default='PRIMARY', max_length=50)),
                ('coxarthrosis_grade', models.IntegerField(choices=[(0, '0 — Нет изменений'), (1, 'I — Сомнительные признаки'), (2, 'II — Минимальные изменения'), (3, 'III — Умеренные изменения'), (4, 'IV — Тяжёлые изменения')], default=0)),
                ('preop_xray_date', models.DateField(blank=True, null=True, verbose_name='Дата рентгена до операции')),
                ('postop_xray_date', models.DateField(blank=True, null=True, verbose_name='Дата рентгена после операции')),
                ('has_complications', models.BooleanField(default=False, verbose_name='Осложнения после операции')),
                ('complications_notes', models.TextField(blank=True)),
                ('surgeon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='info_system.surgeon')),
            ],
        ),
        migrations.CreateModel(
            name='Endoprosthesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateField(verbose_name='Дата операции')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель эндопротеза')),
                ('cup_size', models.IntegerField(verbose_name='Чашка, мм (установленная)')),
                ('stem_number', models.CharField(max_length=20, verbose_name='Ножка, номер (установленная)')),
                ('head_size', models.IntegerField(verbose_name='Головка, мм (установленная)')),
                ('planned_cup_size', models.IntegerField(blank=True, null=True, verbose_name='Чашка, мм (планируемая)')),
                ('planned_stem_number', models.CharField(blank=True, max_length=20, verbose_name='Ножка, номер (планируемая)')),
                ('planned_head_immersion', models.FloatField(blank=True, null=True, verbose_name='Глубина погружения от центра вертлуги (мм)')),
                ('acetabular_diameter', models.FloatField(blank=True, null=True, verbose_name='Диаметр вертлужной впадины (мм)')),
                ('head_height', models.FloatField(blank=True, null=True, verbose_name='Высота головки (мм)')),
                ('femoral_offset', models.FloatField(blank=True, null=True, verbose_name='Плечо бедренной кости (мм)')),
                ('acetabular_depth', models.FloatField(blank=True, null=True, verbose_name='Глубина вертлужной впадины (мм)')),
                ('neck_shaft_angle', models.FloatField(blank=True, null=True, verbose_name='Шеечно-диафизарный угол (°)')),
                ('vertical_angle', models.FloatField(blank=True, null=True, verbose_name='Угол вертикального соответствия (°)')),
                ('wiberg_angle', models.FloatField(blank=True, null=True, verbose_name='Угол Виберга (°)')),
                ('cup_inclination', models.FloatField(blank=True, null=True, verbose_name='Угол наклона вертлужного компонента (°)')),
                ('sharp_angle', models.FloatField(blank=True, null=True, verbose_name='Угол Шарпа (°)')),
                ('head_coverage', models.FloatField(blank=True, null=True, verbose_name='Степень покрытия головки (%)')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_system.patient')),
                ('surgeon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='info_system.surgeon')),
            ],
        ),
    ]
