# Generated by Django 5.2.1 on 2025-05-14 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование диагноза')),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='surgeon',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='bmi',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='complications_notes',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='coxarthrosis_grade',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='coxarthrosis_type',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='has_complications',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='height',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='postop_xray_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='preop_xray_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='weight',
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Телефон'),
        ),
        migrations.CreateModel(
            name='RehabilitationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rehab_start', models.DateField(verbose_name='Дата начала реабилитации')),
                ('rehab_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания реабилитации')),
                ('has_complications', models.BooleanField(default=False, verbose_name='Наличие осложнений')),
                ('complication_details', models.TextField(blank=True, verbose_name='Подробности осложнений')),
                ('notes', models.TextField(blank=True, verbose_name='Дополнительные заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='info_system.diagnosis', verbose_name='Диагноз')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_system.patient', verbose_name='Пациент')),
            ],
        ),
        migrations.DeleteModel(
            name='Endoprosthesis',
        ),
        migrations.DeleteModel(
            name='Surgeon',
        ),
    ]
